use_frameworks!

target 'TLButton_Example' do
  pod 'TLButton', :path => '../'

  target 'TLButton_Tests' do
    inherit! :search_paths

    pod 'Quick'
    pod 'Nimble'
    pod 'FBSnapshotTestCase'
    pod 'Nimble-Snapshots'
  end
end
